### ISSUE TITLE
Not run in Linux?

### ISSUE THREAD

**Issue by KivyDesign** [tjpin/PDF-and-TXT-Files-to-Audio#1]
### Hi tjpin:

Found this problem at exec the test.py and the main.py not run in kivy 1.11.1 and python 3.7

![Captura de pantalla -2021-02-01 23-47-07](https://user-images.githubusercontent.com/71107406/106545527-4b183500-64e8-11eb-8d64-f4e1f75d7ccd.png)

**Comment by lazarus-muya** [comment]
First this project was build on Windows.
Second I used pyttsx3 voice engine which require you to have "espeak" installed in your machine.

All paths used are Windows path..
Install espeak for Linux "apt-get install espeak" and change all paths to Linux path.
